# Generated by Django 3.2.9 on 2022-01-26 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendmail',
            old_name='_to',
            new_name='user_email',
        ),
    ]
