# Generated by Django 3.2.9 on 2022-01-26 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_rename__to_sendmail_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendmail',
            old_name='user_email',
            new_name='useremail',
        ),
    ]
